// Code generated by "stringer -type=ValueType"; DO NOT EDIT.

package readstat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValueTypeString-0]
	_ = x[ValueTypeI8-1]
	_ = x[ValueTypeI16-2]
	_ = x[ValueTypeI32-3]
	_ = x[ValueTypeF32-4]
	_ = x[ValueTypeF64-5]
	_ = x[ValueTypeDate-6]
	_ = x[ValueTypeDateTime-7]
	_ = x[ValueTypeDateTimeWithMilliseconds-8]
	_ = x[ValueTypeDateTimeWithMicroseconds-9]
	_ = x[ValueTypeDateTimeWithNanoseconds-10]
	_ = x[ValueTypeTime-11]
}

const _ValueType_name = "ValueTypeStringValueTypeI8ValueTypeI16ValueTypeI32ValueTypeF32ValueTypeF64ValueTypeDateValueTypeDateTimeValueTypeDateTimeWithMillisecondsValueTypeDateTimeWithMicrosecondsValueTypeDateTimeWithNanosecondsValueTypeTime"

var _ValueType_index = [...]uint8{0, 15, 26, 38, 50, 62, 74, 87, 104, 137, 170, 202, 215}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
